# Main configuration for the MyMonitor application.

# ===================================================================
# Monitor-wide settings
# ===================================================================
[monitor]
interval_seconds = 0.05
default_jobs = [4, 8, 16]
metric_type = "pss_psutil"
monitor_core = 0
build_cores_policy = "all_others"
specific_build_cores = ""
skip_plots = false
log_root_dir = "logs"
# The maximum number of unique command lines to cache for process categorization.
# A larger size may use more memory but can improve performance on extremely
# complex builds with a huge variety of commands. Default is 4096.
categorization_cache_size = 4096
# Defines the scanning mode for the pss_psutil collector.
# - "full_scan": (Default, Safe) Scans all system processes that match the
#   project's process_pattern. This is robust but can be slow.
# - "descendants_only": (Fast, Experimental) Only scans the descendants of the
#   main build process. This is much faster but may miss processes if the build
#   system spawns them in a detached way. Use the `verify_process_tree.py`
#   tool to check if this mode is safe for your project.
pss_collector_mode = "full_scan"

# ===================================================================
# Paths to specialized configuration files
# These paths are relative to this config.toml file.
# ===================================================================
[paths]
projects_config = "projects.toml"
rules_config = "rules.toml"
